### PR TITLE
fix(daemon): stub CheckLinger on non-Linux platforms

### PR DESCRIPTION
**Pull request by winjo**
## Summary

`CheckLinger` is only defined in `daemon/systemd.go` with `//go:build linux`, but `cmd/cc-connect/daemon.go:109` calls it unconditionally. This breaks the build on darwin and windows:

```
cmd/cc-connect/daemon.go:109:27: undefined: daemon.CheckLinger
make: *** [build-noweb] Error 1
```

Although the call is guarded at runtime by `strings.Contains(mgr.Platform(), "user")` — which is only ever true for Linux user-mode systemd — Go still needs the symbol to resolve at compile time.

Introduced in #965.

## Fix

Add `daemon/linger_other.go` with `//go:build !linux` that stubs `CheckLinger` to return `enabled=true`. On platforms where linger is not a concept, callers naturally skip the warning.

## Note on CI

This regression slipped through because `.github/workflows/ci.yml` only runs on `ubuntu-latest`. Worth considering a build matrix that adds `macos-latest` and `windows-latest` so this class of bug is caught before merge — happy to send that as a follow-up if you'd like.

## Test plan

- [x] `make build-noweb` succeeds on darwin (arm64)
- [x] `make build-noweb` succeeds on linux (unchanged path)
- [x] `make build-noweb` succeeds on windows

### CODE REVIEW

**Review by chenhg5 — APPROVED** [review]
LGTM. CI green, clean change, well-structured.

**Comment by happyTonakai** [comment]
duplicate with #1052 #1093 and was fixed by 8e04d66bf68eb5c56e7bb4733f35223c61ceb94b

**Comment by chenhg5** [comment]
fixed. Thanks for your pr!
