### PR TITLE
fix(daemon): add CheckLinger stub for non-Linux platforms

### PR DESCRIPTION
**Pull request by happyTonakai**
## Summary

- Add `daemon/linger_stub.go` with `//go:build !linux` to provide a no-op `CheckLinger` implementation for macOS/Windows
- Fixes cross-platform compilation failure introduced by PR #965

## Problem

PR #965 added `daemon.CheckLinger()` call in `cmd/cc-connect/daemon.go` (line 109), but only implemented the function in `daemon/systemd.go` which has `//go:build linux` constraint.

This caused compilation failure on macOS and Windows:

```
cmd/cc-connect/daemon.go:109:27: undefined: daemon.CheckLinger
```

## Solution

Added `daemon/linger_stub.go` with `//go:build !linux` constraint:

```go
//go:build !linux

package daemon

func CheckLinger() (enabled bool, user string) {
    user = os.Getenv("USER")
    if user == "" {
        user = "unknown"
    }
    // Linger is a systemd concept, not applicable on macOS/Windows
    return true, user
}
```

## Test plan

- [x] `go build -o cc-connect ./cmd/cc-connect` passes on macOS
- [x] `GOOS=windows GOARCH=amd64 go build -o cc-connect.exe ./cmd/cc-connect` passes
- [x] `go vet ./daemon/` passes

Fixes cross-platform compilation issue from #965

### CODE REVIEW

**Review by chenhg5 — APPROVED** [review]
LGTM. CI green, clean change, well-structured.

**Comment by happyTonakai** [comment]
## 关闭说明

感谢审核。这个 PR 和上游 main 上的 commit `8e04d66`（v1.3.3-beta.3，修复 Windows 交叉编译）功能上重复了。

### 两个方案对比

| | 我的 PR (#1052) | 官方 (8e04d66) |
|---|---|---|
| 做法 | `daemon/linger_stub.go` + `//go:build !linux`，一个文件覆盖所有非 Linux 平台 | 分别在 `daemon/launchd.go`、`windows.go`、`unsupported.go` 三处各加一份完全相同的 stub |
| 返回值 | `true, user`（语义不准确） | `false, ""`（正确，非 Linux 无 linger 概念） |
| 代码重复 | ✅ 无 | ❌ 完全相同的代码在三个文件中复制粘贴 |

### 为什么没冲突

官方改的是已有文件（`launchd.go`/`windows.go`/`unsupported.go`），我改的是新文件（`linger_stub.go`），Git 按文件合并，互不重叠，所以没有冲突。但若两者都合入，非 Linux 平台会出现 `CheckLinger` 重复定义，编译报错。

### 建议

官方的修复在语义上是正确的（返回 `false, ""`），但把同一个 `CheckLinger() { return false, "" }` 复制粘贴了三份，违反了 DRY 原则（Don't Repeat Yourself）。Go 社区的标准做法是用 build tag 约束的单文件做跨平台 stub（如标准库的 `race.go`/`norace.go` 模式）。

建议 upstream 后续做一个小 cleanup：
1. 删除在 `launchd.go`、`windows.go`、`unsupported.go` 三处添加的 `CheckLinger` 定义
2. 用我的 `daemon/linger_stub.go` + `//go:build !linux` 方案替代，返回值保持 `return false, ""`

这样功能不变，但代码更干净、好维护。

关闭此 PR。
